import type { ServerMapFixture } from './ServerGameTypes.js';

export const KITCHEN_01_FIXTURE: ServerMapFixture = {
  mapId: 'kitchen_01',
  width: 1440,
  height: 810,
  movementBounds: { minX: 80, minY: 80, maxX: 1360, maxY: 730 },
  seekerSpawn: { x: 720, y: 704 },
  seekerFacing: { x: 0, y: -1 },
  hiderSpawns: [
    { x: 189, y: 398 },
    { x: 1190, y: 394 },
    { x: 630, y: 704 },
    { x: 1044, y: 704 }
  ],
  propPool: [
    'wooden_crate',
    'trash_bin',
    'plant_pot',
    'chair',
    'water_bucket',
    'food_basket'
  ],
  propRadiusById: { wooden_crate: 18, trash_bin: 17, plant_pot: 16, chair: 16, water_bucket: 14, food_basket: 16 },
  props: [
    { propInstanceId: 'crate_01', propConfigId: 'wooden_crate', position: { x: 241, y: 268 }, radius: 18, breakable: true, blocksMovement: true, destroyed: false },
    { propInstanceId: 'basket_01', propConfigId: 'food_basket', position: { x: 302, y: 221 }, radius: 16, breakable: true, blocksMovement: true, destroyed: false },
    { propInstanceId: 'bucket_01', propConfigId: 'water_bucket', position: { x: 369, y: 239 }, radius: 14, breakable: true, blocksMovement: true, destroyed: false },
    { propInstanceId: 'chair_01', propConfigId: 'chair', position: { x: 342, y: 322 }, radius: 16, breakable: true, blocksMovement: true, destroyed: false },
    { propInstanceId: 'trash_bin_01', propConfigId: 'trash_bin', position: { x: 1226, y: 243 }, radius: 17, breakable: true, blocksMovement: true, destroyed: false },
    { propInstanceId: 'bucket_02', propConfigId: 'water_bucket', position: { x: 1134, y: 252 }, radius: 14, breakable: true, blocksMovement: true, destroyed: false },
    { propInstanceId: 'basket_02', propConfigId: 'food_basket', position: { x: 1247, y: 338 }, radius: 16, breakable: true, blocksMovement: true, destroyed: false },
    { propInstanceId: 'chair_02', propConfigId: 'chair', position: { x: 1004, y: 241 }, radius: 16, breakable: true, blocksMovement: true, destroyed: false },
    { propInstanceId: 'chair_03', propConfigId: 'chair', position: { x: 581, y: 358 }, radius: 16, breakable: true, blocksMovement: true, destroyed: false },
    { propInstanceId: 'chair_04', propConfigId: 'chair', position: { x: 860, y: 358 }, radius: 16, breakable: true, blocksMovement: true, destroyed: false },
    { propInstanceId: 'chair_05', propConfigId: 'chair', position: { x: 585, y: 511 }, radius: 16, breakable: true, blocksMovement: true, destroyed: false },
    { propInstanceId: 'basket_03', propConfigId: 'food_basket', position: { x: 722, y: 329 }, radius: 16, breakable: true, blocksMovement: true, destroyed: false },
    { propInstanceId: 'plant_01', propConfigId: 'plant_pot', position: { x: 1017, y: 430 }, radius: 16, breakable: true, blocksMovement: true, destroyed: false },
    { propInstanceId: 'crate_02', propConfigId: 'wooden_crate', position: { x: 493, y: 477 }, radius: 18, breakable: true, blocksMovement: true, destroyed: false },
    { propInstanceId: 'crate_03', propConfigId: 'wooden_crate', position: { x: 92, y: 608 }, radius: 18, breakable: true, blocksMovement: true, destroyed: false },
    { propInstanceId: 'crate_04', propConfigId: 'wooden_crate', position: { x: 266, y: 657 }, radius: 18, breakable: true, blocksMovement: true, destroyed: false },
    { propInstanceId: 'crate_05', propConfigId: 'wooden_crate', position: { x: 358, y: 592 }, radius: 18, breakable: true, blocksMovement: true, destroyed: false },
    { propInstanceId: 'basket_04', propConfigId: 'food_basket', position: { x: 428, y: 673 }, radius: 16, breakable: true, blocksMovement: true, destroyed: false },
    { propInstanceId: 'bucket_03', propConfigId: 'water_bucket', position: { x: 527, y: 621 }, radius: 14, breakable: true, blocksMovement: true, destroyed: false },
    { propInstanceId: 'chair_06', propConfigId: 'chair', position: { x: 338, y: 722 }, radius: 16, breakable: true, blocksMovement: true, destroyed: false },
    { propInstanceId: 'trash_bin_02', propConfigId: 'trash_bin', position: { x: 1143, y: 596 }, radius: 17, breakable: true, blocksMovement: true, destroyed: false },
    { propInstanceId: 'trash_bin_03', propConfigId: 'trash_bin', position: { x: 1258, y: 664 }, radius: 17, breakable: true, blocksMovement: true, destroyed: false },
    { propInstanceId: 'plant_02', propConfigId: 'plant_pot', position: { x: 1058, y: 664 }, radius: 16, breakable: true, blocksMovement: true, destroyed: false },
    { propInstanceId: 'plant_03', propConfigId: 'plant_pot', position: { x: 1244, y: 569 }, radius: 16, breakable: true, blocksMovement: true, destroyed: false },
    { propInstanceId: 'bucket_04', propConfigId: 'water_bucket', position: { x: 988, y: 731 }, radius: 14, breakable: true, blocksMovement: true, destroyed: false },
    { propInstanceId: 'basket_05', propConfigId: 'food_basket', position: { x: 1184, y: 736 }, radius: 16, breakable: true, blocksMovement: true, destroyed: false },
    { propInstanceId: 'crate_06', propConfigId: 'wooden_crate', position: { x: 878, y: 646 }, radius: 18, breakable: true, blocksMovement: true, destroyed: false },
    { propInstanceId: 'chair_07', propConfigId: 'chair', position: { x: 1010, y: 569 }, radius: 16, breakable: true, blocksMovement: true, destroyed: false },
    { propInstanceId: 'trash_bin_04', propConfigId: 'trash_bin', position: { x: 97, y: 414 }, radius: 17, breakable: true, blocksMovement: true, destroyed: false },
    { propInstanceId: 'plant_04', propConfigId: 'plant_pot', position: { x: 1314, y: 387 }, radius: 16, breakable: true, blocksMovement: true, destroyed: false },
    { propInstanceId: 'bucket_05', propConfigId: 'water_bucket', position: { x: 1376, y: 266 }, radius: 14, breakable: true, blocksMovement: true, destroyed: false },
    { propInstanceId: 'basket_06', propConfigId: 'food_basket', position: { x: 1316, y: 474 }, radius: 16, breakable: true, blocksMovement: true, destroyed: false },
    { propInstanceId: 'chair_08', propConfigId: 'chair', position: { x: 690, y: 650 }, radius: 16, breakable: true, blocksMovement: true, destroyed: false },
    { propInstanceId: 'crate_07', propConfigId: 'wooden_crate', position: { x: 760, y: 724 }, radius: 18, breakable: true, blocksMovement: true, destroyed: false },
    { propInstanceId: 'basket_07', propConfigId: 'food_basket', position: { x: 1380, y: 690 }, radius: 16, breakable: true, blocksMovement: true, destroyed: false }
  ],
  obstacles: [
    { obstacleId: 'obstacle_fridge', position: { x: 120, y: 130 }, size: { width: 72, height: 100 }, blocksMovement: true, allowsOverlap: false },
    { obstacleId: 'obstacle_sink_counter', position: { x: 292, y: 110 }, size: { width: 170, height: 44 }, blocksMovement: true, allowsOverlap: false },
    { obstacleId: 'obstacle_stove', position: { x: 1088, y: 108 }, size: { width: 198, height: 48 }, blocksMovement: true, allowsOverlap: false },
    { obstacleId: 'obstacle_pantry', position: { x: 1300, y: 120 }, size: { width: 58, height: 98 }, blocksMovement: true, allowsOverlap: false },
    { obstacleId: 'obstacle_center_table', position: { x: 655, y: 410 }, size: { width: 138, height: 66 }, blocksMovement: true, allowsOverlap: false },
    { obstacleId: 'obstacle_crate_shelf', position: { x: 152, y: 610 }, size: { width: 48, height: 60 }, blocksMovement: true, allowsOverlap: false },
    { obstacleId: 'obstacle_upper_left_pillar_base', position: { x: 459, y: 247 }, size: { width: 38, height: 24 }, blocksMovement: true, allowsOverlap: false },
    { obstacleId: 'obstacle_tall_plant_corner_base', position: { x: 1352, y: 705 }, size: { width: 30, height: 24 }, blocksMovement: true, allowsOverlap: false }
  ],
};
