import type { ServerMapFixture } from './ServerGameTypes.js';

export const KITCHEN_01_FIXTURE: ServerMapFixture = {
  mapId: 'kitchen_01',
  width: 1280,
  height: 720,
  seekerSpawn: { x: 640, y: 626 },
  seekerFacing: { x: 0, y: -1 },
  hiderSpawns: [
    { x: 168, y: 354 },
    { x: 1058, y: 350 },
    { x: 408, y: 626 },
    { x: 928, y: 626 },
  ],
  propPool: ['wooden_crate', 'trash_bin', 'plant_pot', 'chair', 'water_bucket', 'food_basket'],
  propRadiusById: {
    wooden_crate: 24,
    trash_bin: 22,
    plant_pot: 20,
    chair: 20,
    water_bucket: 18,
    food_basket: 20,
  },
  props: [
    {
      propInstanceId: 'crate_03',
      propConfigId: 'wooden_crate',
      position: { x: 174, y: 540 },
      radius: 24,
      breakable: true,
      destroyed: false,
    },
    {
      propInstanceId: 'bucket_03',
      propConfigId: 'water_bucket',
      position: { x: 468, y: 552 },
      radius: 18,
      breakable: true,
      destroyed: false,
    },
    {
      propInstanceId: 'chair_03',
      propConfigId: 'chair',
      position: { x: 516, y: 318 },
      radius: 20,
      breakable: true,
      destroyed: false,
    },
    {
      propInstanceId: 'basket_03',
      propConfigId: 'food_basket',
      position: { x: 664, y: 358 },
      radius: 20,
      breakable: true,
      destroyed: false,
    },
    {
      propInstanceId: 'plant_02',
      propConfigId: 'plant_pot',
      position: { x: 940, y: 590 },
      radius: 20,
      breakable: true,
      destroyed: false,
    },
    {
      propInstanceId: 'trash_bin_02',
      propConfigId: 'trash_bin',
      position: { x: 1016, y: 530 },
      radius: 22,
      breakable: true,
      destroyed: false,
    },
  ],
};
